services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
  mysql-container:
    image: mysql
    ports: 
      - '3306:3306'
    volumes:
      - /Users/gaojinlong/ThisMac/coding/docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD='ginlon'
  redis-container:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - /Users/gaojinlong/ThisMac/coding/docker/redis:/data